### ISSUE TITLE
ToDo's and Ideas

### ISSUE THREAD

**Issue by CM000n** [CM000n/ha-ambilight-hue#1]
- [ ] Check why the switch can no longer be switched off once it has been switched on in Home Assistant
- [ ] Check whether the reaction time for the synchronization of the lights with the Ambilight can be shortened (currently approx. ~ 8 seconds delay)
- [ ] Create your Python library for the connection to the TV and the calculation of various Ambilight values, and outsource it to PyPi?
- [ ] Check how several lights and positions can be set using only one switch config in Home Assistant.
- [ ] Include an automatic check as to which TV URL (depending on the Jointspace version) should be used.
- [ ] Generate a config flow for the HA GUI to set it up
